**6.16** **LIST** **2** **DIMENSI**

List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list.
Penggambarannya seperti sebuah matrik.

In [ ]:
#contoh list dua dimensi pada matrix

matrik = [ 
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]
#mendeklarasikan matrik

print (matrik)



[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [ ]:
matrik [1][2]
#memanggil elemen matrix ke 2 pada matrix 1

7

In [ ]:
matrik [1][2]=100
#mengganti elemen matrik ke 2 pada matrik 1
#matrik 1 terdiri dari [5,6,7,8] dan elemen ke 2 dari matrik 2 yaitu 7
#jadi 7 diganti dengan 100, sehingga 7 telah terganti dengan 100

print (matrik[1][2])
#karena tadi diatas elemen ke 2 tlah diganti dengan 100 maka elemen sebelumnya akan tenggelam dan terganti dengan 100

100


In [ ]:
#Latihan ke 1
#membuat list 2 dimensi dengan menginput sendiri elemen elemennya

list_dua_dimensi = []

jumlah_baris = int(input("Masukkan jumlah baris: "))
jumlah_kolom = int(input("Masukkan jumlah kolom: "))
#Input jumlah baris dan kolom yg diinginkan

print ("\n")
for i in range(jumlah_baris):
#Mengisi list dua dimensi
    
    baris = []
    #Membuat list sementara untuk setiap baris
    for j in range(jumlah_kolom):
        nilai = int(input(f"Masukkan nilai untuk baris {i+1}, kolom {j+1}: "))
        #Input nilai untuk setiap elemen pada baris ke pertama smpai terakhir
        #dan meng input nilai untuk setiap elemen pada kolom pertama sampai terakhir
        #jika kolom dan barisnya lebih dari 1 maka elemen tiap baris dan kolom harus di input hingga mencapai baris dan kolom terakhir
        #jika tidak memasukkan elemen pada baris dan kolom maka akan eror
        baris.append(nilai)
        #Menambahkan nilai ke dalam baris
    list_dua_dimensi.append(baris)
    #Menambahkan baris ke dalam list dua dimensi


print("\nList dua dimensi:")
#Menampilkan list dua dimensi
for baris in list_dua_dimensi:
    print(baris)


Masukkan jumlah baris: 3
Masukkan jumlah kolom: 3


Masukkan nilai untuk baris 1, kolom 1: 2
Masukkan nilai untuk baris 1, kolom 2: 1
Masukkan nilai untuk baris 1, kolom 3: 0
Masukkan nilai untuk baris 2, kolom 1: 0
Masukkan nilai untuk baris 2, kolom 2: 0
Masukkan nilai untuk baris 2, kolom 3: 0
Masukkan nilai untuk baris 3, kolom 1: 8
Masukkan nilai untuk baris 3, kolom 2: 0
Masukkan nilai untuk baris 3, kolom 3: 89

List dua dimensi:
[2, 1, 0]
[0, 0, 0]
[8, 0, 89]


**5.17** **TUPLES**

Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. Jika kita
memiliki data yang tidak ingin dirubah isinya, kita gunakan tuples, sedangkan
jika datanya masih ingin dimanipulasi kedepannya, gunakan list

In [ ]:
#CONTOH TUPLES

angka = (0, 4, 1, 2, 3, 4, 5)
print (angka[0])
print (angka[0:3])
for isi in angka [0:3]:
    print (isi)

#angka [0] = 10
#angka.append(10)
#angka.remove(5)
#pada tuples data yg sudah dimasukkan tidak bisa diganti ataupun diubah ataupun ditambahkan
#contohnya pada diatas jika kita ingin mengubah data maka akan eror

angka.count(4)
#menghitung jumlah munculnya angka yg dimasukkan

angka.index(4)
#menampilkan index ke-n

0
(0, 4, 1)
0
4
1


1

In [ ]:
#LATIHAN KE 1 MEMBUAT TUPLES
#Tuples dapat digunakan untuk menyimpan sekumpulan data yang tetap atau konstan, 
#dan digunakan dalam berbagai operasi seperti pengulangan, pengkondisian, serta pencarian dengan menggunakan metode seperti count() dan index().

#mendeskripsikan tuples terlebih dahulu
tuples_1 = (1, 2, 3, 4, 5) 
#Tuples tipe angka
tuples_2 = ('apel', 'jeruk', 'mangga') 
#Tuples tipe string
tuples_3 = (1.1, 'hello', True) 
#Tuples dengan tipe data yang berbeda

#menampilkan isi tuples
print ("\n")
print("Isi tuples_1:", tuples_1)
print("Isi tuples_2:", tuples_2)
print("Isi tuples_3:", tuples_3)

#mengakses elemen dalam tuple
print ("\n")
print("Elemen pertama dalam tuples_1:", tuples_1[0])
#menampilkan elemen urutan ke 0 pada tuples_1 yaitu 1
print("Elemen kedua dalam tuples_2:", tuples_2[1])
#menampilkan elemen urutan ke 1 pada tuples_2 yaitu jeruk
print("Elemen ketiga dalam tuples_3:", tuples_3[2])
#menampilkan elemen dengan urutan ke 2 pada tuples_3 yaitu True
#karena perhitungan program di python itu dimulai dari 0 maka yg elemen yg ingin ditampilkan +1

#Tuples bersarang (nested tuples)
print ("\n")
tuples_4 = ((1, 2, 3), ('a', 'b', 'c'), (True, False, True))
print("Tuples bersarang:", tuples_4)
#karena data dari tuples tidak bisa dirubah
#maka disini saya menambahkan variabel baru pada tuples yg tida merubah data sebelumnya di tuples

#Menggunakan fungsi len() untuk menghitung panjang tuples
print ("\n")
print("Panjang tuples_1:", len(tuples_1))
#menghitung ada berapa banyak elemen pada tuples_1
print("Panjang tuples_2:", len(tuples_2))
#menghitung ada berapa banyak elemen pada tuples_2

#Tuples bersifat immutable (tidak dapat diubah)
#misalnya, tuple_1[0] = 10 akan menghasilkan error

#menggunakan tuples dalam pengulangan (loop)
for elemen in tuples_2:
    print(elemen)

#menggunakan tuples dalam pengkondisian (conditional)
print ("\n")
if 'apel' in tuples_2:
    print("Apel ada dalam tuples_2.")
#menampilkan suatu elemen yg terdapat di tuples
#contohnya disini saya ingin memunculkan kata 'apel' pada tuples_2
#karena benar adanya kata 'apel' pada tuples_2 maka hasilnya akan sesuai yg di print
#tetapi jika kata yg dicari tdk ada pad tuples tsb maka hasilnya tidak ada

#menggunakan metode count() dan index() untuk melakukan pencarian dalam tuples
print ("\n")
print("Jumlah jeruk dalam tuples_2:", tuples_2.count('jeruk'))
#fungsi count yaitu untuk menghitung berapa kali elemen itu muncul padda data tuples
#disini contohnya saya ingin mencari berapa kali kata jeruk muncul pada tuples_2

print("Indeks mangga dalam tuples_2:", tuples_2.index('mangga'))
#fungsi index yaitu untuk memunculkan elemen itu terdapat pada index atau urutan keberapa dalam program





Isi tuple_1: (1, 2, 3, 4, 5)
Isi tuple_2: ('apel', 'jeruk', 'mangga')
Isi tuple_3: (1.1, 'hello', True)


Elemen pertama dalam tuple_1: 1
Elemen kedua dalam tuple_2: jeruk
Elemen ketiga dalam tuple_3: True


Tuple bersarang: ((1, 2, 3), ('a', 'b', 'c'), (True, False, True))


Panjang tuple_1: 5
Panjang tuple_2: 3
apel
jeruk
mangga


Apel ada dalam tuple_2.


Jumlah jeruk dalam tuple_2: 1
Indeks mangga dalam tuple_2: 2


In [ ]:
#LATIHAN KE 2 TUPLES

#mendeskripsikan tuple berisi nama dan nilai mahasiswa
nilai_mahasiswa1 = ('John', [85, 90, 78, 92])
nilai_mahasiswa2 = ('Jane', [78, 88, 92, 76])
nilai_mahasiswa3 = ('Tom', [92, 95, 89, 88])

#menampilkan nilai mahasiswa
print("\nNilai Mahasiswa 1:")
print("Nama: ", nilai_mahasiswa1[0])
#menampilkan nama mahasiswa_1, 
#karena elemen nama terletak pada index ke 0 makanya yg dipanggil itu index ke 0
print("Nilai: ", nilai_mahasiswa1[1])
#menampilkan nilai mahasiswa_1
#karena nilai  itu elemen ke 1 makanya yg dipanggil yaitu index ke 1

print("\nNilai Mahasiswa 2:")
print("Nama: ", nilai_mahasiswa2[0])
#sama seperti sebelumnya, nama itu elemen ke 0 jadi yg dipanggil index ke 0
print("Nilai: ", nilai_mahasiswa2[1])
#karena nilai itu elemen ke 1 pada nilai_mahasiswa2 maka yg dipanggil yaitu index ke 1

print("\nNilai Mahasiswa 3:")
print("Nama: ", nilai_mahasiswa3[0])
print("Nilai: ", nilai_mahasiswa3[1])

#Program di atas menggunakan tuples untuk menyimpan data nilai mahasiswa
#Setiap tuple berisi nama mahasiswa dan daftar nilai dalam bentuk list 
#Data nilai mahasiswa kemudian diakses dan ditampilkan menggunakan indexing pada tuples.



Nilai Mahasiswa 1:
Nama:  John
Nilai:  [85, 90, 78, 92]

Nilai Mahasiswa 2:
Nama:  Jane
Nilai:  [78, 88, 92, 76]

Nilai Mahasiswa 3:
Nama:  Tom
Nilai:  [92, 95, 89, 88]


**5.18** **DICTIONARIES**

Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data
seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan
data yang bersumber dari orang tersebut

In [ ]:
#contoh dictionaries
#merubah angka menjadi sebuah huruf dari sebutan angka tsb

angka = {
    "0" : "nol",
    "1" : "satu",
    "2" : "dua",
    "3" : "tiga",
    "4" : "empat",
    "5" : "lima",
    "6" : "enam",
    "7" : "tujuh",
    "8" : "delapan",
    "9" : "sembilan",
}

nomor_HP = input ("Masukkan nomor HP anda : ")
nomor_angka = ""
for isi in nomor_HP:
    nomor_angka += angka.get(isi) + " "
print (nomor_angka)

Masukkan nomor HP anda : 081250539241
nol delapan satu dua lima nol lima tiga sembilan dua empat satu 


In [ ]:
#LATIHAN KE 1 DICTIONARY
#Data mahasiswa dengan DICTIONARY

#membuat dictionary berisi data mahasiswa
mahasiswa1 = {'nama': 'John Doe', 
              'usia': 21, 
              'universitas': 'Universitas Udayana', 
              'nilai': [85, 90, 78, 92]}

mahasiswa2 = {'nama': 'Jane Smith', 
              'usia': 22, 
              'universitas': 'Universitas Airlangga', 
              'nilai': [78, 88, 92, 76]}

mahasiswa3 = {'nama': 'Tom Brown', 
              'usia': 20, 
              'universitas': 'Universitas Brawijaya', 
              'nilai': [92, 95, 89, 88]}

#menampilkan data mahasiswa
#jika pada tuples memanggil variabel dengan urutan index 
#maka pada dictionaries memanggil data dengan tipe dari index 
#misalkan pada ('nama' : 'John Doe') itu tipe dari index 'John Doe' itu "nama"
#begitupun yg terjadi dengan selanjutnya
print("\nData Mahasiswa 1:")
print("Nama: ", mahasiswa1['nama'])
print("Usia: ", mahasiswa1['usia'])
print("Universitas: ", mahasiswa1['universitas'])
print("Nilai: ", mahasiswa1['nilai'])

print("\nData Mahasiswa 2:")
print("Nama: ", mahasiswa2['nama'])
print("Usia: ", mahasiswa2['usia'])
print("Universitas: ", mahasiswa2['universitas'])
print("Nilai: ", mahasiswa2['nilai'])

print("\nData Mahasiswa 3:")
print("Nama: ", mahasiswa3['nama'])
print("Usia: ", mahasiswa3['usia'])
print("Universitas: ", mahasiswa3['universitas'])
print("Nilai: ", mahasiswa3['nilai'])



Data Mahasiswa 1:
Nama:  John Doe
Usia:  21
Universitas:  Universitas Udayana
Nilai:  [85, 90, 78, 92]

Data Mahasiswa 2:
Nama:  Jane Smith
Usia:  22
Universitas:  Universitas Airlangga
Nilai:  [78, 88, 92, 76]

Data Mahasiswa 3:
Nama:  Tom Brown
Usia:  20
Universitas:  Universitas Brawijaya
Nilai:  [92, 95, 89, 88]


In [ ]:
#LATIHAN KE 2
#Konversi mata uang menggunakan dictionary

#mendeskripsikan nilai mata uang 
konversi_mata_uang = {"USD": 15000, 
                      "EUR": 17500, 
                      "JPY": 130, 
                      "GBP": 20000}

#mengakses dan menampilkan nilai konversi mata uang
mata_uang = input("Masukkan kode mata uang (USD, EUR, JPY, GBP): ")
#menginput kode mata uang dengan salah satu tipe dari (USD, EUR, JPY, GBP)
jumlah_uang = float(input("Masukkan jumlah uang: "))
#pada kondisi yg ini masukkan nilai mata uang yg ingin dikonversi dari rupiah ke mata uang yg kita masukkan sebelumnya

kurs = konversi_mata_uang.get(mata_uang)
#disini kurs di deklarasikan dulu untuk digunakan dalam if

if kurs:
    jumlah_konversi = jumlah_uang * kurs
    print("Hasil konversi {} {} adalah: {}".format(jumlah_uang, mata_uang, jumlah_konversi))
    #pada proses ini jika data yg di input sesuai dengan deskripsi maka program akan jalan disini terlebih dahulu
    #jika data yg dimasukkan benar pada (USD, EUR, JPY, GBP) sesuai maka outputnya akan hasil dari konversi mata uang tsb
    #tapi jika misalkan tipe mata uang yg kita masukkan dalam huruf kecil maka programnya itu akan melewati ini dan lanjut ke kondisi selanjutnya pada else
else:
    print("Kode mata uang tidak valid.")
    #output ini akan keluar bila data yg dimasukkan tidak sesuai


Masukkan kode mata uang (USD, EUR, JPY, GBP): USD
Masukkan jumlah uang: 20000
Hasil konversi 20000.0 USD adalah: 300000000.0


**5.19** **FUNGSI**

Pada dasarnya fungsi
dibentuk untuk **menghidari** **pengulangan** pembuatan program secara manual
dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang
kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat,
setiap fungsi tersebut dibutuhkan tinggal kita panggil

TUGAS FUNGSI YAITU :
1. menjalankan perintah
2. menampilkan hasil perhitungan

In [ ]:
#contoh fungsi

def full_nama (first_name, last_name):
    print (f"Nama lengkapnya adalah {nama_depan} {nama_belakang}")

first_name = input ("Nama depan anda adalah ")
last_name = input ("Nama belakang anda adalah ")
full_nama (nama_depan, nama_belakang)

Nama belakang anda adalah  = ser
Nama lengkapnya adalah serly nura


In [ ]:
def luas_segitiga (alas,tinggi):
    luas = (1/2) * alas * tinggi
    return luas

In [ ]:
#LATIHAN KE 1 
#MEMBUAT FUNGSI DENGAN MENJALANKAN PERINTAH

#fungsi untuk menambahkan dua angka
def tambah(angka1, angka2):
#disini hanya mendeskripsikan bahwa ada dua angka yg akan dioperasikan
    return angka1 + angka2
    #dua angka akan melakukan operasi penjumlahan apabila sudah terdapat dua angka yg dimasukkan kalau cuman satu maka tida jalan

#fungsi untuk mengurangi dua angka
def kurang(angka1, angka2):
#sama seperti penjumlahan, bahwa di pengurangan membutuhkan dua angka agar bisa menjalankan operasi pengurangan
    return angka1 - angka2
    #pengurangan ini akan berjalan dari angka pertama dikurang dengan angka kedua, tidak dimulai dari angka terbedar
    #sehingga hasil yg keluar bisa merupakan bilangan bertipe int dan juga float

#fungsi untuk mengalikan dua angka
def kali(angka1, angka2):
    return angka1 * angka2

#fungsi untuk membagi dua angka
def bagi(angka1, angka2):
    if angka2 == 0:
        print("Error: Pembagian oleh nol tidak diperbolehkan.")
        return None
#pada fungsi yg menggunakan operasi pembagian yaitu program akan berjalan apabila angka kedua yg dimasukkan tidak sama dengan 0
#yg artinya pembilang dari pembagian tiidak boleh 0
#jika bilangan kedua yaitu 0, maka output yg keluar itu pada kondisi yg pertama
    else:
        return angka1 / angka2
        #jika bilangan kedua tidak sama dengan 0, maka outputnya akan bilangan pertama dibagi dengan bilangan kedua
        #yg terjalankan akan pada kondisi kedua apabila kondisi pertama tidak memenuhi syarat

#fungsi untuk menjalankan perintah yang kita masukkan
def jalankan_perintah():
    while True:
        print("\nPilih operasi:")
        print("1. Tambah")
        print("2. Kurang")
        print("3. Kali")
        print("4. Bagi")
        print("5. Keluar")
        pilihan = input("Masukkan pilihan (1/2/3/4/5): ")
#disini kita deskripsikan dulu untuk memanggil suatu perintah
#disini saya menggunakan while dan kemudian kita disuruh menginput angka dari operasi yg ingin kita hitung

        if pilihan == '5':
            print("Terima kasih telah menggunakan program ini.")
            break
            #apabila kita masukkan angka 5 maka program akan selesai dan tidak menjalankan kondisi selanjutnya

        angka1 = float(input("Masukkan angka pertama: "))
        #memasukkan angka pertama disini bisa berupa tipe data int ataupun float
        angka2 = float(input("Masukkan angka kedua: "))
        #pada angka kedua juga sama bisa berupa tipe data int ataupun float

        if pilihan == '1':
            hasil = tambah(angka1, angka2)
            #apabila angka 1 di input maka kondisi ini akan berproses menghitung dan melanjutkan ke kondisi kedua
        elif pilihan == '2':
            hasil = kurang(angka1, angka2)
            #apabila angka 2 di input maka kondisi ini akan berproses menghitung dan melanjutkan ke kondisi selanjutnya
        elif pilihan == '3':
            hasil = kali(angka1, angka2)
             #apabila angka 3 di input maka kondisi ini akan berproses menghitung dan melanjutkan ke kondisi berikutnya
        elif pilihan == '4':
            hasil = bagi(angka1, angka2)
             #apabila angka 4 di input maka kondisi ini akan berproses menghitung dan melanjutkan ke kondisi selanjutnya
             #jika ada angka yg diinput diluar dari variabel yg di deskripsikan maka outputnya akan berupa pada else dibawah
             #dan program tidak akan terhenti apabila tidak munculnya angka 5 yg melakukan perintah keluar
        else:
            print("\nPilihan tidak valid. Silakan coba lagi.")
            continue

        if hasil is not None:
            print("\nHasil: ", hasil)
            #untuk menghitung hasil dari operasi pada nomor 1,2,3, dan 4

#menjalankan program
jalankan_perintah()

#Program di atas memungkinkan untuk memilih operasi matematika 
#(tambah, kurang, kali, atau bagi) yang ingin dilakukan pada dua angka yang akan dimasukkan. 
#Hasil dari operasi matematika tersebut kemudian ditampilkan. 
#kita dapat mengulangi perintah sebanyak yang diinginkan dan keluar dari program dengan memilih opsi "Keluar"


Pilih operasi:
1. Tambah
2. Kurang
3. Kali
4. Bagi
5. Keluar
Masukkan pilihan (1/2/3/4/5): 1
Masukkan angka pertama: 9
Masukkan angka kedua: 765

Hasil:  774.0

Pilih operasi:
1. Tambah
2. Kurang
3. Kali
4. Bagi
5. Keluar
Masukkan pilihan (1/2/3/4/5): 3
Masukkan angka pertama: 98
Masukkan angka kedua: 99

Hasil:  9702.0

Pilih operasi:
1. Tambah
2. Kurang
3. Kali
4. Bagi
5. Keluar
Masukkan pilihan (1/2/3/4/5): 4
Masukkan angka pertama: 34
Masukkan angka kedua: 0
Error: Pembagian oleh nol tidak diperbolehkan.

Pilih operasi:
1. Tambah
2. Kurang
3. Kali
4. Bagi
5. Keluar
Masukkan pilihan (1/2/3/4/5): 5
Terima kasih telah menggunakan program ini.


**5.20** **NUMPY**

**Numpy** merupakan salah satu Library dalam Python yang memiliki keunggulan
dalam perhitungan menggunakan **vektor** dan **matriks** dalam berbagai dimensi.
Hal pertama yang perlu dilakukan adalah memanggil Library Numpy sebagai
berikut:

In [ ]:
import numpy as np
#memasukkan library numpy pada collab agar bisa digunakan

**5.20.1 PERINTAH DASAR PADA NUMPY**
Berikut akan dipaparkan mengenai beberapa perintah dalam Numpy diantaranya
memanggil Numpy, mengetahui dimensi dan ukuran variabel


In [ ]:
#contoh numpy pada array

a = np.array ([80, 0, 5, 2, 7, 9])
#'a' merupakan sebuah variabel yg mewakili elemen elemen
#'np.array' merupakan tipe data array pada numpy
#disini kita mendeskripsikan sebuah variabel a

print (a)
#menampilkan elemen dari variabel 'a'

[80  0  5  2  7  9]


In [ ]:
b = np.array ([[9, 0.3, 3, 6.5, 2], [2, 5, 0, 3.2, 4], 
               [4, 5, 2.3, 8, 99], [24, 72, 32, 55, 88]])
print (b)

[[ 9.   0.3  3.   6.5  2. ]
 [ 2.   5.   0.   3.2  4. ]
 [ 4.   5.   2.3  8.  99. ]
 [24.  72.  32.  55.  88. ]]


In [ ]:
c = np.array ([[4, 77, 33, 59], [12, 15, 9, 93], 
               [42, 61, 8, ], [90, 89, 88, 87]])
print (c)

[[ 4 77 33 59]
 [12 15  9 93]
 [42 61  8  0]
 [90 89 88 87]]


In [ ]:
#LATIHAN KE 1

import numpy as np

#membuat array numpy
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

#menampilkan array 1 dan array 2
print("Array 1:", array1)
print("Array 2:", array2)

#menghitung operasi penjumlahan pada array
hasil_penjumlahan = array1 + array2
print("\nHasil Penjumlahan:", hasil_penjumlahan)

#menghitung operasi pengurangan pada array
hasil_pengurangan = array1 - array2
print("\nHasil Pengurangan:", hasil_pengurangan)

#menghitung operasi perkalian pada array
hasil_perkalian = array1 * array2
print("\nHasil Perkalian:", hasil_perkalian)

#menghitung operasi pembagian pada array
hasil_pembagian = array1 / array2
print("\nHasil Pembagian:", hasil_pembagian)

#menghitung operasi pangkat pada array
hasil_pangkat = np.power(array1, array2)
#np.power adalah sebuah fungsi pada library numpy di Python yang digunakan untuk menghitung hasil pangkat dari suatu array atau nilai tunggal. 
#np.power mengambil dua argumen, yaitu basis (array atau nilai tunggal) dan eksponen (array atau nilai tunggal) yang ingin dipangkatkan.

print("\nHasil Pangkat:", hasil_pangkat)
#Pada contoh di atas, np.power digunakan untuk menghitung hasil pangkat 
#dari array1 dengan basis array1 dan eksponen array2. 
#Hasil pangkat dari array1 dengan eksponen array2 akan ditampilkan sebagai hasil_pangkat.

#menampilkan mean, nilai minimum, nilai maximum, dan jumlah dari array
print("\nMean Array 1:", np.mean(array1))
#mencari mean dari array 1

print("\nMin Array 2:", np.min(array2))
#menampilkan nilai minimum dari array 2
#pada array 2 yaitu [6,7,8,9,10] maka nilai minimumnya yaitu 6 yg terletak pada index ke 0

print("\nMax Array 1:", np.max(array1))
#sama seperti nilai minimum tadi
#elemen yg terdapat pada array 1 [1,2,3,4,5] maka nilai maximumnya yaitu 5 karena merupakan nilai tertinggi pada array 1

print("\nSum Array 2:", np.sum(array2))
#menjumlahkan semua elemen pada array 2
#array 2 terdiri dari [6,7,8,9,10]
#maka [6+7+8+9+10 = 40]

x = array1.ndim
#fungsi "ndim" digunakan untuk menentukan jumlah dimensi pada numpy
y = array1. shape
#fungsi "shape" digunakan untuk menghitung banyaknya jumlah baris dan kolom kolom array pada numpy
print ("\n Banyaknya baris dalam Arrray 1 : ", x, 
       "\n Banyaknya kolom dalam Array 1 : ",y)

x1 = array2.ndim
y1 = array2.shape
print ("\n Banyaknya baris dalam Arrray 2 : ", x, 
       "\n Banyaknya kolom dalam Array 2 : ",y)


Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]

Hasil Penjumlahan: [ 7  9 11 13 15]

Hasil Pengurangan: [-5 -5 -5 -5 -5]

Hasil Perkalian: [ 6 14 24 36 50]

Hasil Pembagian: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]

Hasil Pangkat: [      1     128    6561  262144 9765625]

Mean Array 1: 3.0

Min Array 2: 6

Max Array 1: 5

Sum Array 2: 40

 Banyaknya baris dalam Arrray 1 :  1 
 Banyaknya kolom dalam Array 1 :  (5,)

 Banyaknya baris dalam Arrray 2 :  1 
 Banyaknya kolom dalam Array 2 :  (5,)


**5.20.2 MEMANGGIL ANGGOTA, KOLOM, DAN BARIS DENGAN NUMPY**

In [ ]:
#LATIHAN memanggil anggota, kolom, dan baris pada numpy

A = np.array ([[1,2,3,4], 
               [1.1,2.2,3.3,4.4], 
               [1,3,5,7], 
               [2,4,6,8], 
               [0,0,0,1]])
#np.array() digunakan untuk membuat matriks NumPy dari list atau array

A[0,3]
#matrix[baris, kolom] digunakan untuk memanggil anggota matriks pada baris dan kolom tertentu
#memanggil data array pada baris ke-0 dan kolom ke-3
#karena data pada array terdpat data float, maka bilangan yg bertipe int mengikuti dengan ,0 dibelakang angka

4.0

In [ ]:
A [1,:]
#menampilkan semua data array pada baris ke-1 
#Jika ingin memanggil seluruh kolom atau baris, kita dapat menggunakan : sebagai indeks.

array([1.1, 2.2, 3.3, 4.4])

In [ ]:
A [:,2]
#menampilkan seluruh data array pada kolom ke-2 

array([3. , 3.3, 5. , 6. , 0. ])

In [ ]:
A [0,1:3]
#menampilkan data array dengan index ke-0, dari kolom 1 sampai 3 dan tidak termasuk kolom ke-3, jadi hanya kolom 1 dan kolom 2 

array([2., 3.])

In [ ]:
A [0,0:3:2]
#menampilkan  data array dengan baris ke-0 dan kolom ke-0 sampai kolom ke-3 dengan lompatan 2 atau dengan selisih 2 kali

array([1., 3.])

In [ ]:
A [0,0] = 100
#mengganti data array baris ke-0 dan kolom ke-0
print (A)

[[100.    2.    3.    4. ]
 [  1.1   2.2   3.3   4.4]
 [  1.    3.    5.    7. ]
 [  2.    4.    6.    8. ]
 [  0.    0.    0.    1. ]]


**5.20.3 MATRIX PADA NUMPY**



In [ ]:
#LATIHAN KE-1 MATRIX PADA NUMPY

import numpy as np

a = np.zeros((10,10))
print ("Matrix dengan ordo 10x10 : \n", a)

b = np.identity(10)
print ("\n Matrix identitas dengan ordo 10x10 : \n", b)

c = 9*b
print ("\n Mengganti nilai dari matrix identitas : \n", c)
#disini artinya merubah elemen dari matrix identitas, matrix c mempunyai diagonal utama dengan angka 9
#karena sebelumnya matrix identitas tsb mempunyai angka 1
#maka disini diubah menjadi 9

d = np.ones((8,8))
#matrix 1 dengan ordo 8x8
e = np.identity(8)*8
#matrix identitas dengan ordo 8x8
f = d + e
#menggabungkan dua buah matrix yaitu matrix 1 dan matrix identitas yg tadi setelah diubah menjadi 9
print ("\n Menggabungkan dua matrix yg memiliki ordo yg sama : \n", f)

c[1:-1,1:-1] = f
print ("\n Mengganti bagian tengah dari matrix c yg berisi nilai dari matrix f :  \n ",c)
#Pernyataan ini mengganti bagian tengah dari matriks c dengan nilai dari matriks f
#Pengindeksan 1:-1 berarti mengambil indeks dari 1 hingga satu sebelum indeks terakhir, 
#yang menghasilkan subset matriks c tanpa baris pertama dan terakhir serta kolom pertama dan terakhir.

g = np.identity(6)*9
# Pernyataan ini membuat matriks identitas 6x6 dengan nilai diagonal utama yang dikalikan dengan 9, 
#dan hasilnya disimpan dalam variabel g.
c [2:-2,2:-2] = g
#Pernyataan ini mengganti bagian tengah matriks c dengan matriks g, 
#menggunakan pengindeksan 2:-2 untuk mengambil subset matriks c tanpa 2 baris pertama dan 2 terakhir serta 2 kolom pertama dan 2 terakhir.
print ("\n Matrix identitas ordo 6x6 dengan diagonal utama dikalikan dengan 9 : \n ", c)

h = np.ones ((4,4))*2
#Pernyataan ini membuat matriks 4x4 dengan semua elemen bernilai 2 menggunakan fungsi np.ones dan mengalikannya dengan 2 untuk menghasilkan matriks h yang berisi semua nilai 2.
i = np.identity(4)*7
#Pernyataan ini membuat matriks identitas 4x4 dengan nilai diagonal utama yang dikalikan dengan 7, dan hasilnya disimpan dalam variabel i.
j = h + i
#Pernyataan ini menjumlahkan matriks h dan i secara elemen-wise, sehingga menghasilkan matriks j yang merupakan penjumlahan dari matriks h dan i.
print ("\n Penggabungan dari Matrix h dan matrix i : \n", j)

c[3:-3,3:-3] = j
#Pernyataan ini mengganti bagian tengah matriks c dengan matriks j menggunakan pengindeksan 3:-3 untuk mengambil subset matriks c tanpa 3 baris pertama dan 3 terakhir serta 3 kolom pertama dan 3 terakhir.
print ("\n Menampilkan matrix dengan mengganti bagian tengah matrix : \n", c)

k = np.identity (2)*9
#Pada baris ini, kita membuat sebuah matriks identitas 2x2 menggunakan fungsi np.identity(2), yang menghasilkan matriks identitas dengan ukuran 2x2. 
#Kemudian, matriks identitas tersebut dikalikan dengan angka 9 menggunakan operator perkalian *, sehingga setiap elemen dalam matriks identitas akan dikalikan dengan 9 
#Hasilnya disimpan dalam variabel k.
c [4:-4,4:-4] = k
#Pada baris ini, kita mengganti bagian tertentu dari matriks c dengan matriks k. 
#Bagian matriks c yang diganti diindeks menggunakan slicing dengan sintaksis [4:-4, 4:-4]
#Slicing ini mengambil potongan dari baris ke-4 hingga baris ke-(n-4), dan kolom ke-4 hingga kolom ke-(n-4), di mana n adalah ukuran matriks c pada dimensi yang sesuai. 
#Kemudian, kita mengganti potongan ini dengan matriks k menggunakan operator =.
print ("\n Matrix identitas dengan pola tertentu : \n", c)


Matrix dengan ordo 10x10 : 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 Matrix identitas dengan ordo 10x10 : 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

 Mengganti nilai dari matrix identitas : 
 [[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 

In [ ]:
#LATIHAN KE-2 MATRIX PADA NUMPY

import numpy as np

a = np.ones((2,3))
print ("Matrix 1 dengan ordo 2x3  : \n", a)
# "np.ones" digunakan untuk membuat matrix dengan ordo tertentu yg elemennya berisi angka 1 pada numpy
# "np.ones((2,3))" pada angka pertama itu untuk menentukan jumlah baris dan angka kedua untuk menentukan jumlah kolom
# misal ((2,3)) yaitu kita akan membuat matrix dengan jumlah baris 2, dan kolomnya berjumlah 3

b = np.zeros((3,2))
print ("\n Matrix 0 dengan ordo 3x2 : \n", b)
# "np.zeros" digunakan untuk membuat matrix dengan seluruh elemennya berisi 0
# ((3,2)) yaitu untuk menentukan jumlah baris, jumlah kolom

c = np.identity (4)
print ("\n Matrix identitas dengan ordo 4x4 : \n", c)
# "np.identity" digunakan untuk membuat matrix identitas
#yaitu matrix dengan ordo yg sama dan memiliki diagonal utama
# "np.identity (4)" angka 4 disini untuk menentukan berapa jumlah ordo yg diinginkan
# karena matrix identitas pastilah bernilai sama baris dan kolomnya, maka hanya satu angka saja yg dimasukkan

d = np.ones ((2,3,4))
print ("\n Akan dibuat 2 data matrix 1 dengan ordo 3x4 : \n", d)
# "np.ones" untuk membuat matrix dengan semua elemennya berisi satu
# "((2,3,4))" angka pertama menunjukkan berapa kali matrix akan dibuat, jadi disini angka 2 karena akan dibentuk 2 matrix
#angka kedua untuk menentukan jumlah baris
#angka ketiga untuk menentukan jumlah kolom
#jadi kesimpulannya, akan dibuat matrix dengan ordo 3x4 sebanyak 2 kali atau ada 2 data matrix yg berordo 3x4

e = np.full ((3,2),9)
print ("\n Matrix 9 dengan ordo 3x2 : \n ", e)
# "np.full" digunakan untuk memanggil matrix dengan isi elemen yg ditentukan sebelumnya
# "((3,2),9)" disini angka pertama dan kedua itu untuk menentukan baris dan kolom
# angka ketiga yaitu sembarang angka yg kita tentukan, contohnya kita ingin matrix yg berisi angka 9 maka bisa dimasukkan angka 9 stelah tanda kurung dari ordo

f = np.random.rand (4,3)
print ("\n Matrix yg mempunyai sebarang elemen dengan ordo 4x3 : \n", f)
# "np.random.rand" untuk memanggil elemen random di baris dan kolom
# "(4,3)" itu untuk jumlah baris, jumlah kolom
#dsini angka random yg akan ditampilkan itu tidak di input sendiri oleh kita, tapi ditentukan oleh program 

g = np.random.randint (1,10, size = (3,4))
print ("\n Matrix dengan sebarang elemen diantara interval 1 hingga 10, dengan ordo 3x4 : \n", g)
# "np.random.randint" digunakan untuk membuat data array berupa matrix dengan sebarang elemen
# dan memiliki batas angka dari elemen dan mempunyai ordo juga
# (1,10, size = (3,4)) disini angka pertama itu "1,10" yg dimana angka ini merupakan batas dari elemen yg ada di matrix
#jadi angka yg ada di matrix tsb berada di interval 1 hingga 10, dan tidak lebih dari 10 dan tidak kurang dari 1
# kemudian "size = (3,4)" ini artinya itu ukuran dari jumlah baris dan kolom, yg dimana berarti mempunyai ordo 3x4

Matrix 1 dengan ordo 2x3  : 
 [[1. 1. 1.]
 [1. 1. 1.]]

 Matrix 0 dengan ordo 3x2 : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

 Matrix identitas dengan ordo 4x4 : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 Akan dibuat 2 data matrix 1 dengan ordo 3x4 : 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

 Matrix 9 dengan ordo 3x2 : 
  [[9 9]
 [9 9]
 [9 9]]

 Matrix yg mempunyai sebarang elemen dengan ordo 4x3 : 
 [[0.60074707 0.05705915 0.16107984]
 [0.61100512 0.1002141  0.4247048 ]
 [0.76525444 0.32012022 0.86534247]
 [0.77361154 0.91898525 0.25100885]]

 Matrix dengan sebarang elemen diantara interval 1 hingga 10, dengan ordo 3x4 : 
 [[9 3 5 9]
 [6 5 5 3]
 [2 2 4 1]]


**5.20.4 COPY PADA NUMPY**

operasi penyalinan (copy) digunakan untuk membuat **salinan independen dari suatu objek array**, sehingga perubahan pada salinan tersebut tidak akan mempengaruhi objek array asli. 

In [ ]:
#LATIHAN KE-1 COPY PADA NUMPY

import numpy as np

a = np.array ([1,2,3,4,5])
print ("Menampilkan data a array : \n", a)
#Pada baris ini, kita membuat array numpy dengan nama a yang berisi elemen-elemen [1, 2, 3, 4, 5]

b = a
print ("\n Menampilkan data b array yg dimana b=a : \n", b)
#menyamakan variabel baru dengan yg ada di data
#Pada baris ini, kita membuat variabel b yang merupakan alias dari array a
#Dalam numpy, jika kita membuat variabel baru yang mengacu pada array yang sudah ada, itu hanya akan menjadi referensi (alias) ke array asli, bukan salinan baru.

b[0] = 10
print ("\nData array terbaru setelah diubah : \n", b)
#mengganti index ke 0 dengan elemen baru yaitu 10 

print ("\n Memanggil data a array setelah diperbarui : \n", a)
#memanggil variabel a, karena diatas tadi di deskripsikan  bahwa b = a, maka sama artinya dengan a = b

c = np.array ([9,8,7,6,5])
print ("\n Menampilkan data array c : \n", c)
#Pada baris ini, kita membuat array numpy baru dengan nama c yang berisi elemen-elemen [9, 8, 7, 6, 5].

d = c.copy()
print ("\n Mengcopy data array c ke data array d : \n", d)
#Pada baris ini, kita membuat salinan dalam (deep copy) dari array c dan menyimpannya dalam variabel d.
#Ini akan membuat array baru yang sepenuhnya independen dari c, sehingga perubahan pada d tidak akan mempengaruhi c.

d[0] = 10
print ("\n Menampilkan data array d setelah ada perubahan : \n", d)
#Pada baris ini, kita mengganti nilai elemen pertama dari array d menjadi 10.

print ("\n Menampilkan data array c : \n", c)
#menampilkan data array c

Menampilkan data a array : 
 [1 2 3 4 5]

 Menampilkan data b array yg dimana b=a : 
 [1 2 3 4 5]

Data array terbaru setelah diubah : 
 [10  2  3  4  5]

 Memanggil data a array setelah diperbarui : 
 [10  2  3  4  5]

 Menampilkan data array c : 
 [9 8 7 6 5]

 Mengcopy data array c ke data array d : 
 [9 8 7 6 5]

 Menampilkan data array d setelah ada perubahan : 
 [10  8  7  6  5]

 Menampilkan data array c : 
 [9 8 7 6 5]


In [ ]:
#LATIHAN KE-2 COPY PADA NUMPY

import numpy as np

#Membuat array asal
a = np.array([1, 2, 3, 4, 5])

#Menggunakan copy() untuk membuat salinan array baru
b = np.copy(a)

#Mengubah nilai pada array b
b[0] = 10

#Mencetak isi array a dan b
print("Elemen dari data array a terdiri dari : \n", a)
print("\n Elemen dari data array b terdiri dari : \n", b)


Elemen dari data array a terdiri dari : 
 [1 2 3 4 5]

 Elemen dari data array b terdiri dari : 
 [10  2  3  4  5]


**5.20.5 OPERASI MATEMATIKA PADA NUMPY**

In [ ]:
#LATIHAN KE-1 OPERASI MATEMATIKA

import numpy as np

#mendeskripsikan nilai array dari variabel pada numpy
a = np.array ([2,2,8,8,9,9])
b = np.array ([1,1,3,3,7,7])
print ("Data array a terdiri dari : \n", a)
print ("Data array b terdiri dari : \n", b, "\n")

#menggunakan operasi penjumlahan pada array
s1 = a + 2
print ("Hasil dari a + 2 : \n", s1, "\n")
#pada baris ini artinya menambahkan 2 ke setiap elemen dalam array a

#menggunakan operasi pengurangan di array pada numpy
s2 = a - 2
print ("Hasil dari a - 2 : \n", s2, "\n")
#pada baris ini artinya mengurangi 2 dari setiap elemen dalam array a

#operasi perkalian pada array di numpy
s3 = a*2
print ("Hasil dari a * 2 : \n", s3, "\n")
#Mengalikan setiap elemen dalam array a dengan 2.

#menggunakan operasi pembagian di array pada numpy
s4 = a/2
print ("Hasil dari a / 2 : \n", s4, "\n")
#Membagi setiap elemen dalam array a dengan 2.

#menggunakan operasi kuadrat di array pada numpy
s5 = a**2
print ("Hasil dari a ** 2 : \n", s5, "\n")
#Mengkuadratkan setiap elemen dalam array a.

#operasi penjumlahan dua data array pada numpy
s6 = a+b
print ("Hasil dari a + b : \n", s6, "\n")
#Menjumlahkan elemen per elemen antara array a dan b jika ukurannya sama.

#operasi pengurangan dua data array pada numpy
s7 = a-b
print ("Hasil dari a - b : \n", s7, "\n")
#Mengurangkn elemen per elemen antara array a dan b jika ukurannya sama.

#operasi perkalian dua data array pada numpy
s8 = a*b
print ("Hasil dari a * b : \n", s8, "\n")
#mengalikan elemen per elemen antara array a dan b jika ukurannya sama.

#operasi pembagian dua data array pada numpy
s9 = a/b
print ("Hasil dari a / b : \n", s9, "\n")
#Membagi elemen per elemen antara array a dan b jika ukurannya sama.

#operasi perpangkatan dua data array pada numpy
s10 = b**a
print ("Hasil dari b**a: \n", s10, "\n")
#Menghitung nilai b pangkat a untuk setiap elemen dalam array a.

#operasi pembentukan nilai cos (a)
t1 = np.cos(a)
print ("Hasil dari cos(a) : \n", t1, "\n")
#Menghitung kosinus dari setiap elemen dalam array a.

#operasi pembentukan nilai sin (a)
t2 = np.sin(a)
print ("Hasil dari sin(a) : \n", t2, "\n")
#Menghitung sinus dari setiap elemen dalam array a.

#operasi pembentukan nilai tangen (a)
t3 = np.tan(a)
print ("Hasil dari tan(a) : \n", t3, "\n")
#Menghitung tangen dari setiap elemen dalam array a.

#operasi pembentukan sinus hiperbolik (a)
t4 = np.sinh(a)
print ("Hasil dari sinh(a) : \n", t4, "\n")
#Menghitung sinus hiperbolik dari setiap elemen dalam array a.

#operasi pembentukan kosinus hiperbolik (a)
t5 = np.cosh(a)
print ("Hasil dari cosh(a) : \n", t5, "\n")
#Menghitung kosinus hiperbolik dari setiap elemen dalam array a.

#operasi pembentukan tangen hiperbolik (a)
t6 = np.tanh(a)
print ("Hasil dari tanh(a) : \n", t6, "\n")
#Menghitung tangen hiperbolik dari setiap elemen dalam array a.

#operasi yang menghitung nilai dari akar kuadrat (a)
t7 = np.sqrt(a)
print ("Hasil dari akar kuadrat (a) : \n", t7, "\n")
#Menghitung akar kuadrat dari setiap elemen dalam array a.

Data array a terdiri dari : 
 [2 2 8 8 9 9]
Data array b terdiri dari : 
 [1 1 3 3 7 7] 

Hasil dari a + 2 : 
 [ 4  4 10 10 11 11] 

Hasil dari a - 2 : 
 [0 0 6 6 7 7] 

Hasil dari a * 2 : 
 [ 4  4 16 16 18 18] 

Hasil dari a / 2 : 
 [1.  1.  4.  4.  4.5 4.5] 

Hasil dari a ** 2 : 
 [ 4  4 64 64 81 81] 

Hasil dari a + b : 
 [ 3  3 11 11 16 16] 

Hasil dari a - b : 
 [1 1 5 5 2 2] 

Hasil dari a * b : 
 [ 2  2 24 24 63 63] 

Hasil dari a / b : 
 [2.         2.         2.66666667 2.66666667 1.28571429 1.28571429] 

Hasil dari b**a: 
 [       1        1     6561     6561 40353607 40353607] 

Hasil dari cos(a) : 
 [-0.41614684 -0.41614684 -0.14550003 -0.14550003 -0.91113026 -0.91113026] 

Hasil dari sin(a) : 
 [0.90929743 0.90929743 0.98935825 0.98935825 0.41211849 0.41211849] 

Hasil dari tan(a) : 
 [-2.18503986 -2.18503986 -6.79971146 -6.79971146 -0.45231566 -0.45231566] 

Hasil dari sinh(a) : 
 [3.62686041e+00 3.62686041e+00 1.49047883e+03 1.49047883e+03
 4.05154190e+03 4.05154190e+03]

**5.20.6 PERKALIAN MATRIK PADA NUMPY**

Dapat diamati bahwa operasi matematika pada suatu matrik dengan Numpy
akan mengoperaikan elemen yang baris dan kolomnya sama. Tentunya hal ini
akan memberikan hasil berbeda jika yang kita kehendaki adalah perkalian dua
matrik. **Perkalian matrik pada Numpy** dapat menggunakan perintah **matmul**.
Perlu dijadikan perhatian tentang ukuran matrik yang akan dikalikan harus
sesuai dengan persyaratan. Misalnya matrik ukuran (2x3) dapat dikalikan dengan matrik ukuran (3x4).

In [ ]:
#LATIHAN KE-1 PERKALIAN MATRIK

import numpy as np

#membuat 2 array dengan fungsi "np.array"
a = np.array ([[1,2,3,4], [5,6,7,8]])
b = np.array ([[9,10,11,12], [13,14,15,16]])
print ("Data pada arrray a : \n", a, "\n")
print ("Data pada array b : \n", b, "\n")

c = a*b
print ("Hasil dari perkalian data a x  b : \n", c, "\n")
#Selanjutnya, kita mengalikan kedua array a dan b menggunakan operator *, yang merupakan perkalian element-wise
#Hasilnya disimpan dalam array c. Dalam perkalian element-wise, elemen pada posisi yang sama pada kedua array dikalikan

e = np.array ([[9,10], [11,12], [13,14], [15,16]])
print (e)
#membuat array 2 dimensi e dengan menggunakan fungsi np.array()

f = np.matmul(a,e)
print (f)
#melakukan operasi perkalian matriks antara array a dan e menggunakan fungsi np.matmul(), dan hasilnya disimpan dalam variabel f. 
#Operasi perkalian matriks ini dilakukan sesuai dengan aturan perkalian matriks, yaitu jumlah kolom pada matriks pertama harus sama dengan jumlah baris pada matriks kedua.



Data pada arrray a : 
 [[1 2 3 4]
 [5 6 7 8]] 

Data pada array b : 
 [[ 9 10 11 12]
 [13 14 15 16]] 

Hasil dari perkalian data a x data b : 
 [[  9  20  33  48]
 [ 65  84 105 128]] 

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
[[130 140]
 [322 348]]


**5.20.7 MIN, MAX DAN SUM PADA NUMPY**

Perintah min, max dan sum cukup sering digunakan untuk mengetahui nilai
minimum, maksimum dan penjumlahan.


In [ ]:
#LATIHAN KE-1 

a = np.array ([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print ("Data array a : \n", a, "\n")
#mendeklarasikan data array pada variabel a

b = np.min(a)
print ("Nilai minimum dari data a yaitu : \n", b, "\n")
#menampilkan nilai minimum pada data array a
#menggunakan fungsi "np.min()" untuk mencari nilai minimum dari data array pada numpy

c = np.min(a, axis = 0)
print ("Nilai minimum data a pada setiap kolom yaitu : \n", c, "\n")
#digunakan untuk mencari nilai minimum (elemen terkecil) dari setiap kolom dalam array a menggunakan axis=0
#Hasilnya disimpan dalam array c

d = np.min(a, axis = 1)
print("Nilai minimum data a pada setiap baris yaitu : \n", d, "\n")
#digunakan untuk mencari nilai minimum (elemen terkecil) dari setiap baris dalam array a menggunakan axis=1
#Hasilnya disimpan dalam array d

e = np.max (a)
print ("Nilai maximum pada data array a yaitu : \n", e, "\n")
#digunakan untuk mencari nilai maksimum (elemen terbesar) dari seluruh elemen dalam array a
#Hasilnya disimpan dalam variabel e

f = np.max (a, axis = 0)
print ("Nilai maximum data a pada setiap kolom yaitu : \n", f, "\n")
#digunakan untuk mencari nilai maksimum (elemen terbesar) dari setiap kolom dalam array a menggunakan axis=0
#Hasilnya disimpan dalam array f

g = np.max (a, axis = 1)
print ("Nilai maximum data a pada setiap baris yaitu : \n", g, "\n")
#digunakan untuk mencari nilai maksimum (elemen terbesar) dari setiap baris dalam array a menggunakan axis=1. Hasilnya disimpan dalam array g

h1 = np.sum (a)
print ("Jumlah dari data array a yaitu : \n", h1, "\n")
#digunakan untuk menjumlahkan seluruh elemen dalam array a. Hasilnya disimpan dalam variabel h

h2 = np.sum (a, axis = 0)
print ("Jumlah dari data a pada setiap kolom yaitu : \n", h2, "\n")
#digunakan untuk menjumlahkan setiap kolom dalam array a menggunakan axis=0. Hasilnya disimpan dalam array h


i = np.sum (a, axis = 1)
print ("Jumlah dari data a pada setiap baris yaitu : \n", i, "\n")
#digunakan untuk menjumlahkan setiap baris dalam array a menggunakan axis=1. Hasilnya disimpan dalam array i


Data array a : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Nilai minimum dari data a yaitu : 
 1 

Nilai minimum data a pada baris yaitu : 
 [1 2 3 4] 

Nilai minimum data a pada kolom yaitu : 
 [1 5 9] 

12
[ 9 10 11 12]
[ 4  8 12]
78
[15 18 21 24]
[10 26 42]
